categories:
  - name: "Database & Persistence"
    subcategories:
      - name: "SQL"
        patterns:
          - ".*mysql.*"
          - ".*postgresql.*"
          - ".*h2.*"
          - "org\\.hibernate.*"
          - "com\\.oracle.*"
      - name: "NoSQL"
        patterns:
          - "org\\.mongodb.*"
  - name: "Messaging & Event Streaming"
    patterns:
      - "org\\.apache\\.kafka.*"
      - "org\\.springframework\\.kafka.*"
      - "org\\.springframework\\.amqp.*"
      - "com\\.rabbitmq.*"
      - "org\\.apache\\.activemq.*"
  - name: "Web & Application Frameworks"
    subcategories:
      - name: "Spring: Boot"
        patterns:
          - "^org\\.springframework\\.boot.*"
          - "^spring-boot.*"
      - name: "Spring: Framework"
        patterns:
          - "^org\\.springframework\\.(?!boot).*"
          - "^spring-framework.*"
          - "^spring-core.*"
          - "^spring-context.*"
          - "^spring-web.*"
      - name: "Other Web Frameworks"
        patterns:
          - "jakarta\\.servlet.*"
          - "javax\\.servlet.*"
          - "org\\.apache\\.struts.*"
          - "org\\.jsf.*"
  - name: "Application Servers & Runtime Containers"
    patterns:
      - "org\\.apache\\.tomcat.*"
      - "org\\.jboss.*"
      - "org\\.eclipse\\.jetty.*"
      - "io\\.undertow.*"
      - "com\\.oracle\\.weblogic.*"
      - "com\\.ibm\\.websphere.*"
  - name: "Security & Authentication"
    patterns:
      - "org\\.springframework\\.security.*"
      - "org\\.apache\\.shiro.*"
      - "org\\.keycloak.*"
      - "javax\\.security.*"
  - name: "Caching & In-Memory Data Stores"
    patterns:
      - "org\\.ehcache.*"
      - "com\\.hazelcast.*"
      - "org\\.redis.*"
      - "net\\.sf\\.ehcache.*"
      - "com\\.infinispan.*"
  - name: "Logging, Monitoring & Observability"
    patterns:
      - "org\\.apache\\.logging.*"
      - "org\\.slf4j.*"
      - "ch\\.qos\\.logback.*"
      - "io\\.micrometer.*"
      - "com\\.newrelic.*"
  - name: "Testing, Quality Assurance & Mocking"
    patterns:
      - "org\\.junit.*"
      - "org\\.testng.*"
      - "org\\.mockito.*"
      - "org\\.hamcrest.*"
  - name: "Cloud, Containerization & Orchestration"
    patterns:
      - "org\\.springframework\\.cloud.*"
      - "io\\.fabric8.*"
      - "org\\.kubernetes.*"
      - "com\\.docker.*"
  - name: "Build, Dependency Management & Deployment Tools"
    patterns:
      - "org\\.apache\\.maven.*"
      - "org\\.gradle.*"
      - "org\\.sonatype.*"
  - name: "Data Serialization, Transformation & Processing"
    patterns:
      - "com\\.fasterxml\\.jackson.*"
      - "com\\.google\\.gson.*"
      - "javax\\.json.*"
      - "org\\.json.*"
  - name: "Networking & Communication"
    patterns:
      - "org\\.apache\\.http.*"
      - "com\\.okhttp3.*"
      - "org\\.springframework\\.webclient.*"
  - name: "Utility & Helper Libraries"
    patterns:
      - "org\\.apache\\.commons.*"
      - "com\\.google\\.guava.*"
      - "org\\.apache\\.commons\\.lang.*"
      - "org\\.apache\\.commons\\.io.*"
  - name: "User Interface & Client-Side"
    patterns:
      - "javax\\.swing.*"
      - "javafx\\..*"
      - "org\\.eclipse\\.swt.*"
  - name: "Documentation, Code Generation & Development Tools"
    patterns:
      - "io\\.swagger.*"
      - "org\\.springdoc.*"
      - "org\\.asciidoctor.*"
      - "org\\.javadoc.*"
  - name: "Analytics, Machine Learning & Big Data"
    patterns:
      - "org\\.apache\\.spark.*"
      - "org\\.apache\\.flink.*"
      - "org\\.tensorflow.*"
      - "org\\.deeplearning4j.*"
      - "org\\.apache\\.mahout.*"
